/**
 * The isolated signer's wire contract (A-005, §3.1, §9 step 3).
 *
 * §3.1: "The signer exposes no generic sign-bytes method. It independently recomputes the
 * canonical action hash, checks the current mandate and policy, confirms an allow verdict,
 * and signs only the defined receipt payload."
 *
 * That sentence is the whole design brief, and this file is where it is made mechanical:
 *
 *   - There are exactly two methods, `status` and `evaluateAndSign`. There is no `sign`,
 *     no `signDigest`, no `signBytes`, and no method that takes a hash and returns a
 *     signature over it. Adding one would void the public "isolated signer" claim.
 *
 *   - `evaluateAndSign` accepts *typed fields*, never a prepared digest. The signer builds
 *     the DecisionReceiptPayload itself and signs the EIP-712 digest it derived. There is
 *     no parameter through which a caller supplies bytes to be signed: `evidenceHash` is
 *     computed from the full bundle, `reasonCodesHash` from the validated code set,
 *     `actionHash` from the typed action, and `decisionId` is generated by the signer.
 *
 *     PRECISELY WHAT THAT DOES AND DOES NOT GUARANTEE, because the first version of this
 *     comment overclaimed and an adversarial review called it: on the ALLOW path every
 *     32-byte field is derived by the signer or checked against the vault's live state. On
 *     the BLOCK and REVIEW paths, `mandateHash`, `policyHash`, and `simulationBlockHash`
 *     may carry values the signer flagged but did not reject — that is the point of those
 *     verdicts, since a receipt that blocks a stale or unverifiable action must be able to
 *     record what was claimed. Such a receipt is EVIDENCE ABOUT A CLAIMED ACTION, never
 *     authority: the vault executes neither verdict, and the discrepancy is recorded in the
 *     reason codes the receipt commits to. What holds unconditionally is the narrower and
 *     more important property — a caller cannot obtain a signature over bytes of its own
 *     choosing, because EIP-712 type and domain separation mean the result is only ever
 *     interpretable as a DecisionReceiptPayload for this chain and this vault.
 *
 *   - Wire numbers are decimal strings, parsed here into bigint. JSON has no integer type
 *     that survives a uint256, and a silently-truncated value in a security payload is a
 *     defect, not an inconvenience.
 *
 * The parsers below are the RPC's input validation. They are strict on purpose: an
 * unrecognised field is an error rather than something quietly ignored, because "the
 * caller sent a field the signer dropped" is exactly how a payload comes to mean two
 * different things to two components.
 */

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

export type Hex = `0x${string}`;

/** §5 verdict. Mirrors SentinelTypes.Verdict; BLOCK is the zero value and the default. */
export const VERDICT = {BLOCK: 0, REVIEW: 1, ALLOW: 2} as const;
export type VerdictName = keyof typeof VERDICT;

export function verdictNumber(v: VerdictName): number {
    return VERDICT[v];
}

// ---------------------------------------------------------------------------
// Reason codes and their severity
// ---------------------------------------------------------------------------

/**
 * What a failed signer check *does* depends on which of three tiers it belongs to. This
 * taxonomy is the most security-relevant decision in the signer, so it is stated once,
 * here, rather than being implied by scattered `if` statements.
 *
 * FATAL — the request is internally inconsistent or addressed to a different system.
 *   The signer cannot honestly attest to anything, including a BLOCK. No receipt is
 *   produced for any verdict.
 *
 * EXECUTABILITY — the receipt could not possibly be executed, or the signer is not the
 *   key the vault currently recognises. ALLOW and REVIEW are refused, because both are
 *   execution paths (a REVIEW receipt executes with an owner override, §3.3(7)). BLOCK
 *   is still signed: a block receipt is evidence, never authority, and evidence about a
 *   stale action is still true evidence.
 *
 * CONFORMANCE — a finding the *evaluator* is supposed to have weighed. ALLOW is refused,
 *   because §3.3(8) requires that stale, conflicting, or unverifiable state never produce
 *   an automatic allow. REVIEW is permitted, and this is load-bearing rather than lax:
 *   Case 4 (§4.2) is triggered by exactly these conditions — a changed target code hash,
 *   a proxy target, conflicting anchored state — and its expected result is a REVIEW
 *   receipt. A signer that refused to sign on a code-hash mismatch would make Case 4
 *   unreachable, i.e. it would break the spec while looking stricter.
 *
 * The asymmetry is deliberate and worth restating: severity bounds what the signer will
 * ATTEST to. It never widens it. There is no tier at which a failing check makes an
 * ALLOW more likely.
 */
export type Severity = "FATAL" | "EXECUTABILITY" | "CONFORMANCE";

export const REASON_SEVERITY = {
    // --- FATAL: refuse every verdict ---------------------------------------
    /** action.dataHash does not equal keccak256(callData) — the payload contradicts itself. */
    SIGNER_DATAHASH_MISMATCH: "FATAL",
    /** action.vault is not the vault this signer serves. */
    SIGNER_WRONG_VAULT: "FATAL",
    /** action.chainId is not the chain this signer is connected to. */
    SIGNER_WRONG_CHAIN: "FATAL",
    /** The vault could not be read. Fail closed (§3.3(8)); an unread vault is not a green light. */
    SIGNER_VAULT_UNREACHABLE: "FATAL",
    /**
     * The chain would not hold still long enough for the signer to observe one block.
     *
     * D-055(c). `readVaultState` pins every read to a single block and then confirms that
     * block is still the head; if that never holds within `SNAPSHOT_ATTEMPTS`, there is no
     * consistent state to attest against and the signer says so.
     *
     * IT COVERS TWO CONDITIONS, NOT ONE (R2-F6, D-055(e), CONFIRMED at INFO). The earlier
     * wording named only chain movement. The retry loop `continue`s on EITHER of:
     *   (a) the head MOVED — a different block, or the same height with a different hash
     *       (a reorg), so the pin went stale; or
     *   (b) the head had NO HASH — a pending block, which cannot be anchored to at all and
     *       which no amount of retrying will change if the node keeps serving one.
     * Exhausting the attempts on (b) is not "the chain is moving too fast"; it is "the node
     * never offered a finalised head". **A record naming one cause for two conditions is the
     * shape this project keeps paying for.** The signed RefusalRecord has no detail field; SIGNER_CHAIN_UNSTABLE remains one public code for both (a) and (b). Distinguishing text exists only on ChainUnstableError, which attest.ts does not put on the wire.
     * No reason-code split: the tiering and the remedy are identical, and splitting a public
     * code to carry a diagnostic belongs in the detail, not in the enum (D-057(4)).
     *
     * FATAL, and it is a SEPARATE code from SIGNER_VAULT_UNREACHABLE on purpose. Both refuse
     * everything, so the tiering does not distinguish them — the RECORD does. "The vault
     * could not be read" and "the vault was read repeatedly and the chain moved each time"
     * are different facts, and filing the second as the first would put a claim in the
     * refusal record that the evidence does not support. That substitution is the honesty
     * defect this project exists to study, so it is not made here to save a constant.
     */
    SIGNER_CHAIN_UNSTABLE: "FATAL",
    /**
     * The domain separator the signer derived does not match the one the vault reports.
     * This is a live cross-language differential check between this TypeScript
     * implementation and the Solidity library, and a mismatch means every signature this
     * process could produce would be rejected onchain. Refusing is the only honest move.
     */
    SIGNER_DOMAIN_SEPARATOR_MISMATCH: "FATAL",
    /** callData is shorter than a 4-byte selector, so no supported call can be described. */
    SIGNER_CALLDATA_TOO_SHORT: "FATAL",
    /**
     * The evidence bundle's decoded parameters do not match what the calldata actually says.
     *
     * D-014. The signer decodes the bytes itself and compares. FATAL rather than
     * CONFORMANCE: this is not a judgement about the action, it is a bundle that
     * misdescribes the action it is evidence for. Attesting to it — even to say BLOCK —
     * would put a false statement into the record the receipt commits to.
     */
    SIGNER_EVIDENCE_DECODING_MISMATCH: "FATAL",
    /**
     * The evidence bundle carries no decoded-parameters claim the signer can check.
     *
     * D-014 requires the bundle's decoding to be signer-attested. An optional attestation is
     * worthless — a caller wishing to lie would simply omit the field — so an absent or
     * unparseable claim is refused rather than skipped.
     */
    SIGNER_EVIDENCE_DECODING_ABSENT: "FATAL",

    // --- EXECUTABILITY: refuse ALLOW and REVIEW ----------------------------
    /** The vault's active signer is not this signer's address (rotated out, or never set). */
    SIGNER_NOT_ACTIVE_SIGNER: "EXECUTABILITY",
    /** action.actionNonce is not the vault's current nonce. */
    SIGNER_NONCE_MISMATCH: "EXECUTABILITY",
    /** The vault is paused; nothing executes (§3.3 pause invariant). */
    SIGNER_VAULT_PAUSED: "EXECUTABILITY",
    /** The action deadline has already passed. */
    SIGNER_ACTION_EXPIRED: "EXECUTABILITY",
    /**
     * An executable receipt already exists for this (chain, vault, nonce) naming a
     * different action, and it has not expired. See `attest.ts` for why the signer keeps
     * this guard at all.
     */
    SIGNER_NONCE_ALREADY_ATTESTED: "EXECUTABILITY",

    // --- CONFORMANCE: refuse ALLOW only ------------------------------------
    /** The supplied MandatePayload does not hash to the vault's active mandate hash. */
    SIGNER_MANDATE_NOT_ACTIVE: "CONFORMANCE",
    /** The owner-signed mandate does not authorise this vault's active isolated signer. */
    SIGNER_MANDATE_SIGNER_MISMATCH: "CONFORMANCE",
    /** The supplied PolicyPayload does not hash to the vault's active policy hash. */
    SIGNER_POLICY_NOT_ACTIVE: "CONFORMANCE",
    /** action.mandateHash / action.policyHash do not match the vault's active hashes. */
    SIGNER_ACTION_BINDING_STALE: "CONFORMANCE",
    /** The mandate names a different target than the action calls. */
    SIGNER_MANDATE_TARGET_MISMATCH: "CONFORMANCE",
    /** The mandate names a different selector than the calldata carries. */
    SIGNER_MANDATE_SELECTOR_MISMATCH: "CONFORMANCE",
    /** The action's native value exceeds the mandate's ceiling. */
    SIGNER_MANDATE_VALUE_EXCEEDED: "CONFORMANCE",
    /** Now is outside the mandate's validAfter/validUntil window. */
    SIGNER_MANDATE_WINDOW: "CONFORMANCE",
    /** The mandate's principal is not the vault's current owner (§5.1). */
    SIGNER_MANDATE_PRINCIPAL_MISMATCH: "CONFORMANCE",
    /** The mandate's policyHash does not match the policy bound into the action. */
    SIGNER_MANDATE_POLICY_LINK_MISMATCH: "CONFORMANCE",
    /** Mandate vault/chain fields disagree with the action. */
    SIGNER_MANDATE_SCOPE_MISMATCH: "CONFORMANCE",
    /**
     * The target's runtime code hash is not the one the mandate pinned. This is a Case 4
     * trigger, which is why it is CONFORMANCE and not EXECUTABILITY.
     */
    SIGNER_TARGET_CODEHASH_MISMATCH: "CONFORMANCE",
    /**
     * The recorded simulation block hash is not the chain's at that height — the anchored
     * state the verdict was computed against cannot be confirmed.
     *
     * CONFORMANCE, and this tiering was wrong at first. §4.2 Case 4 lists its triggers in
     * one sentence: "The target code hash changes, the target appears to be a proxy, **the
     * anchored RPC state conflicts, or simulation is unavailable**." All four have the same
     * expected result — review. This code was originally EXECUTABILITY, which refuses
     * REVIEW, so half of a ratified demonstration case could never produce the receipt the
     * spec requires. The first two triggers were tiered correctly and their siblings in the
     * same sentence were not; an adversarial review caught it.
     *
     * The general rule the mistake illustrates, worth keeping: a check whose subject is
     * EVIDENCE QUALITY belongs in CONFORMANCE, because "we cannot confirm this" is exactly
     * what a review verdict is for. EXECUTABILITY is only for facts that make the receipt
     * unusable — a consumed nonce, a paused vault, a rotated-out signer.
     */
    SIGNER_SIMULATION_BLOCK_MISMATCH: "CONFORMANCE",
    /**
     * The receipt's anchor names a block that is not the one the signer read the vault at.
     *
     * D-055(c), the E3 repair, and the difference from the code above is the whole point.
     * SIGNER_SIMULATION_BLOCK_MISMATCH asks "is this a real block?" — which any historical
     * block answers yes to, which is why an ALLOW could be anchored arbitrarily far back,
     * including to a block at which the vault had no code, and still execute. This asks "is
     * this THE block whose state I just checked?", and only one block per request can be.
     *
     * D-055(c) chose that over a recency bound deliberately: a permitted-age number is a
     * policy parameter nobody had reasoned about, whereas consistency needs no parameter and
     * is the property that was actually missing — the signer attests against the state it
     * read. An old anchor is refused as a CONSEQUENCE of disagreeing with the snapshot, not
     * because a threshold declared it too old.
     *
     * CONFORMANCE, by the rule the code above states: the subject is EVIDENCE QUALITY, and
     * §4.2 Case 4 lists "the anchored RPC state conflicts" as a REVIEW trigger. This is that
     * sentence's condition read literally — the anchor and the signer's observation conflict
     * — so ALLOW is refused and REVIEW remains reachable.
     */
    SIGNER_ANCHOR_NOT_OBSERVED: "CONFORMANCE",
    /** Policy vault/chain fields disagree with the action. */
    SIGNER_POLICY_SCOPE_MISMATCH: "CONFORMANCE",
    /** The policy's allowedOperation is not the action's operation. */
    SIGNER_POLICY_OPERATION_MISMATCH: "CONFORMANCE",
    /** The action's native value exceeds the policy's ceiling. */
    SIGNER_POLICY_VALUE_EXCEEDED: "CONFORMANCE",
    /** Now is outside the policy's validAfter/validUntil window. */
    SIGNER_POLICY_WINDOW: "CONFORMANCE",
    /** The action's operation is not CALL, the only operation v0.2 supports (§4). */
    SIGNER_UNSUPPORTED_OPERATION: "CONFORMANCE",
    /** The vault's immutable native-value cap would reject this action. */
    SIGNER_VAULT_VALUE_CAP_EXCEEDED: "CONFORMANCE",
    /** The vault's target allowlist would reject this action. */
    SIGNER_VAULT_TARGET_NOT_ALLOWED: "CONFORMANCE",
    /** The vault's selector allowlist would reject this action. */
    SIGNER_VAULT_SELECTOR_NOT_ALLOWED: "CONFORMANCE",
} as const satisfies Record<string, Severity>;

export type ReasonCode = keyof typeof REASON_SEVERITY;

export function severityOf(code: ReasonCode): Severity {
    return REASON_SEVERITY[code];
}

/**
 * Whether a set of signer findings permits attesting to `verdict`.
 *
 * Reads as a table rather than nested conditionals because this is the function a
 * reviewer will want to check by eye against the tier documentation above.
 */
export function refusesVerdict(codes: ReasonCode[], verdict: VerdictName): boolean {
    return codes.some((c) => {
        switch (severityOf(c)) {
            case "FATAL":
                return true;
            case "EXECUTABILITY":
                return verdict !== "BLOCK";
            case "CONFORMANCE":
                return verdict === "ALLOW";
        }
    });
}

/**
 * The only shape a reason code may take.
 *
 * Not decoration. `canonicalReasonCodes` joins with "\n" and sorts, and BOTH of those need
 * this constraint to mean anything:
 *
 *   - WITHOUT A DELIMITER BAN the encoding is not injective. The single code
 *     "A\nB" and the pair ["A", "B"] produce identical bytes and therefore an identical
 *     `reasonCodesHash`. Since the code list itself travels outside the receipt and only
 *     the hash is signed, a caller could hand a verifier a list that hashes correctly while
 *     hiding a signer finding inside another element. `reasonCodesHash` is the receipt's
 *     only in-payload commitment to WHY Sentinel decided what it did.
 *
 *   - WITHOUT AN ASCII RESTRICTION the sort is not portable. JavaScript's default sort
 *     compares UTF-16 code units; Python — mandated by D-010 for the independent verifier —
 *     compares code points. The two disagree above U+FFFF, so the same set of codes would
 *     canonicalise differently in the two implementations and the verifier would report a
 *     mismatch on a correct receipt. Restricted to this charset, code-unit and code-point
 *     order coincide, and the D-010 reimplementation is a plain `sorted()`.
 *
 * Both were found by adversarial review rather than by writing the code.
 */
export const REASON_CODE_PATTERN = /^[A-Za-z0-9_.:-]{1,64}$/;

/**
 * Canonical encoding of the reason-code set that `reasonCodesHash` commits to.
 *
 * Sorted, de-duplicated, newline-joined, UTF-8. Deliberately trivial: the D-010 verifier
 * reimplements this from the written schema in another language, and every degree of
 * freedom here is a place two implementations can disagree while both believing they are
 * right. Sorting removes order as a variable; de-duplication removes multiplicity; and
 * `REASON_CODE_PATTERN`, enforced at the RPC boundary, removes the delimiter and the
 * collation as variables.
 *
 * Throws rather than sanitising: silently dropping a malformed code would remove a finding
 * from the record the receipt commits to.
 */
export function canonicalReasonCodes(codes: readonly string[]): string {
    for (const code of codes) {
        if (!REASON_CODE_PATTERN.test(code)) {
            throw new ProtocolError(
                `reason code ${JSON.stringify(code)} is not ${REASON_CODE_PATTERN.source}`,
            );
        }
    }
    return [...new Set(codes)].sort().join("\n");
}

// ---------------------------------------------------------------------------
// Payload types (§5), bigint-valued
// ---------------------------------------------------------------------------

export interface MandatePayload {
    schemaVersion: bigint;
    mandateId: Hex;
    principal: Hex;
    /** The isolated signer explicitly authorised by the owner-signed mandate. */
    signer: Hex;
    vault: Hex;
    chainId: bigint;
    target: Hex;
    targetCodeHash: Hex;
    selector: Hex;
    maxNativeValueWei: bigint;
    purposeKind: Hex;
    resourceId: Hex;
    beneficiary: Hex;
    durationSeconds: bigint;
    recurringAllowed: boolean;
    validAfter: bigint;
    validUntil: bigint;
    policyHash: Hex;
}

/**
 * INERT SIGNED FIELDS, named exhaustively (R3-F4, D-055(e); accepted at D-057(6)).
 *
 * Four fields across the §5 payloads are SIGNED, HASHED and CONSULTED BY NOTHING. Measured,
 * not inferred: `ts/src/evaluate/checks.ts` reads each of them zero times, and
 * `contracts/src/SentinelVault.sol` reads each of them zero times.
 *
 *   - `PolicyPayload.allowedCallGraphHash`  — ALREADY DISCLOSED (D-025 reserved it; the class
 *                                             coverage guard states it is read by nothing)
 *   - `PolicyPayload.allowedTargetsHash`    — NEWLY DISCLOSED 2026-08-19
 *   - `PolicyPayload.allowedSelectorsHash`  — NEWLY DISCLOSED 2026-08-19
 *   - `MandatePayload.purposeKind`          — NEWLY DISCLOSED 2026-08-19
 *
 * **They are COMMITTED/RESERVED METADATA, not enforced policy.** Being in the payload hash
 * makes them tamper-evident: a bundle cannot change them without changing the hash the receipt
 * commits to. It does NOT make them enforced, and no implementation should be read as
 * consulting them.
 *
 * **WHAT ACTUALLY ENFORCES TARGETS AND SELECTORS**, so the hashes are not mistaken for it: the
 * vault's own onchain `allowedTarget` / `allowedSelector` mappings, surfaced as
 * `SIGNER_VAULT_TARGET_NOT_ALLOWED` and `SIGNER_VAULT_SELECTOR_NOT_ALLOWED` — the SIGNER_
 * prefix is the real one. This comment first cited an `EVAL_` spelling that exists nowhere
 * in the codebase, caught by the D-057(5) verifier: a disclosure whose enforcement pointer
 * names a fictitious code is a claim nobody can follow. The hashes commit to a
 * list; the mappings are what refuses an action.
 */
export interface PolicyPayload {
    schemaVersion: bigint;
    policyVersion: bigint;
    vault: Hex;
    chainId: bigint;
    allowedOperation: bigint;
    allowedTargetsHash: Hex;
    allowedSelectorsHash: Hex;
    maxNativeValueWei: bigint;
    maxAllowanceIncreaseBaseUnits: bigint;
    allowedCallGraphHash: Hex;
    validAfter: bigint;
    validUntil: bigint;
    failureMode: bigint;
}

export interface ActionPayload {
    schemaVersion: bigint;
    chainId: bigint;
    vault: Hex;
    actionNonce: bigint;
    target: Hex;
    valueWei: bigint;
    dataHash: Hex;
    operation: bigint;
    mandateHash: Hex;
    policyHash: Hex;
    deadline: bigint;
}

/**
 * §5.5. The owner's override for a REVIEW receipt.
 *
 * The isolated signer never produces or handles one of these — it is signed by the human
 * owner, and §3.3(7) is precisely that the review path needs a credential the signer cannot
 * mint. Declared here because the type belongs to the §5 schema set and the review path is
 * exercised end-to-end in the tests.
 */
export interface OverrideAuthorizationPayload {
    schemaVersion: bigint;
    reviewReceiptHash: Hex;
    actionHash: Hex;
    mandateHash: Hex;
    policyHash: Hex;
    actionNonce: bigint;
    reasonHash: Hex;
    issuedAt: bigint;
    expiresAt: bigint;
}

export interface DecisionReceiptPayload {
    schemaVersion: bigint;
    decisionId: Hex;
    actionHash: Hex;
    mandateHash: Hex;
    policyHash: Hex;
    verdict: bigint;
    reasonCodesHash: Hex;
    evidenceHash: Hex;
    simulationBlockNumber: bigint;
    simulationBlockHash: Hex;
    issuedAt: bigint;
    expiresAt: bigint;
    signer: Hex;
}

// ---------------------------------------------------------------------------
// Requests and responses
// ---------------------------------------------------------------------------

export interface EvaluateAndSignRequest {
    action: ActionPayload;
    /** The complete calldata. The signer hashes it; it never trusts action.dataHash. */
    callData: Hex;
    /** The mandate the evaluator believes is active. Its hash is checked against the vault. */
    mandate: MandatePayload;
    /** The policy the evaluator believes is active. Its hash is checked against the vault. */
    policy: PolicyPayload;
    evaluation: {
        verdict: VerdictName;
        /** The evaluator's own reason codes. The signer appends its findings and hashes the union. */
        reasonCodes: string[];
        /**
         * The canonical evidence-bundle bytes (§5.6: RFC 8785 JSON), passed in full.
         *
         * The signer hashes these itself rather than accepting an `evidenceHash`. Accepting
         * a caller-supplied 32 bytes would be a narrow but real generic-signing surface —
         * "put these bytes inside a structure I will sign" — and the whole point of A-005
         * is that no such surface exists. The cost is that the bundle crosses a local
         * socket; the benefit is that the signer never signs a digest it did not compute.
         */
        evidenceCanonical: string;
        simulationBlockNumber: bigint;
        simulationBlockHash: Hex;
    };
    /** Requested receipt lifetime. Clamped by the signer to its max and to the action deadline. */
    ttlSeconds?: bigint;
}

export interface SignedReceipt {
    receipt: DecisionReceiptPayload;
    signature: Hex;
    /** The exact ordered list that `reasonCodesHash` commits to, so a verifier can recompute it. */
    reasonCodes: string[];
    actionHash: Hex;
    evidenceHash: Hex;
    /** The signer's findings, separated from the evaluator's for the audit trail. */
    signerFindings: ReasonCode[];
}

/**
 * §D-012. Proof that the signer saw a request and declined it.
 *
 * WHY THIS EXISTS. Before D-012 a refusal produced only an absent receipt, so "the signer
 * refused" and "the signer was never asked" were indistinguishable — meaning Gate S2 could
 * not prove the signer had ever seen a request at all.
 *
 * WHY IT IS NOT A DecisionReceiptPayload. A refusal is not a decision. Reusing the receipt
 * type would create an artifact a careless reader could mistake for one, and would put a
 * verdict field on something that carries no verdict. It is a distinct structure with a
 * distinct signing domain (see `refusalDigest`), so it can never be presented as a receipt
 * and the vault can never accept it — there is no code path that would even parse it.
 */
export interface RefusalRecord {
    schemaVersion: bigint;
    chainId: bigint;
    vault: Hex;
    /** The action the signer was asked about, so the refusal is attributable to a request. */
    actionHash: Hex;
    /** Hash of the evidence the caller supplied, binding the refusal to that evidence. */
    evidenceHash: Hex;
    requestedVerdict: VerdictName;
    /** keccak256 over the canonical reason-code set, same encoding as a receipt's. */
    reasonCodesHash: Hex;
    refusedAt: bigint;
    signer: Hex;
}

export interface Refusal {
    refused: true;
    /** The findings that blocked attestation, with the tier each fell in. */
    blocking: {code: ReasonCode; severity: Severity}[];
    signerFindings: ReasonCode[];
    requestedVerdict: VerdictName;
    /**
     * The signed refusal artifact (D-012), or null when the request was too malformed to
     * attribute — a payload contradicting its own calldata names no action the signer could
     * honestly say it refused.
     */
    refusalRecord: {record: RefusalRecord; signature: Hex; reasonCodes: string[]} | null;
}

export type EvaluateAndSignResult = ({refused: false} & SignedReceipt) | Refusal;

export interface StatusResult {
    /** The signer's address. The only thing this process ever reveals about its key. */
    signerAddress: Hex;
    vault: Hex;
    chainId: string;
    /** True when the vault is readable and reports this signer as active. */
    ready: boolean;
    notes: string[];
}

// ---------------------------------------------------------------------------
// Wire parsing
// ---------------------------------------------------------------------------

export class ProtocolError extends Error {}

function fail(path: string, expected: string): never {
    throw new ProtocolError(`${path}: expected ${expected}`);
}

function obj(v: unknown, path: string): Record<string, unknown> {
    if (typeof v !== "object" || v === null || Array.isArray(v)) fail(path, "an object");
    return v as Record<string, unknown>;
}

/** Decimal-string → bigint. Rejects hex, signs, exponents, and anything else clever. */
function uint(v: unknown, path: string): bigint {
    if (typeof v !== "string" || !/^(0|[1-9][0-9]*)$/.test(v)) {
        fail(path, "an unsigned decimal integer string");
    }
    return BigInt(v);
}

/**
 * Reject strings containing an unpaired UTF-16 surrogate.
 *
 * A-044. `evidenceHash` is `keccak256(stringToBytes(evidenceCanonical))`, and viem's
 * `stringToBytes` is `TextEncoder.encode`, which replaces EVERY unpaired surrogate with
 * U+FFFD. So `"x\ud800y"` and `"x\udbffy"` encode to the same bytes and hash identically —
 * verified directly. All 2,048 lone surrogates collapse to one sequence, so k of them give
 * 2048^k distinct bundles sharing an `evidenceHash`, and the receipt's commitment to its
 * evidence stops being injective.
 *
 * Symmetry with the independent verifier is the second reason and arguably the better one:
 * the D-010 CLI now rejects lone surrogates under RFC 8785 §3.2.2.2, where such data "MUST
 * cause a compliant JCS implementation to terminate with an appropriate error". Before this
 * check the signer would sign evidence that verifier structurally could not reproduce — a
 * genuine receipt reading as FAILED. Both sides now agree on what is signable.
 *
 * This does NOT establish that the string is canonical JSON; §5.6 requires that and the
 * signer still takes the caller's word for it. Stated so the check is not over-read.
 */
function wellFormed(s: string, path: string): string {
    if (/[\uD800-\uDFFF]/.test(s.replace(/[\uD800-\uDBFF][\uDC00-\uDFFF]/g, ""))) {
        fail(path, "well-formed UTF-16 with no unpaired surrogate (RFC 8785 §3.2.2.2)");
    }
    return s;
}

function bounded(v: unknown, path: string, bits: number): bigint {
    const n = uint(v, path);
    if (n >= 1n << BigInt(bits)) fail(path, `a uint${bits}`);
    return n;
}

function hex(v: unknown, path: string, bytes?: number): Hex {
    if (typeof v !== "string" || !/^0x[0-9a-fA-F]*$/.test(v)) fail(path, "a 0x-prefixed hex string");
    // ODD LENGTHS ARE REJECTED, and this is not pedantry. `callData` has no fixed byte
    // length, and viem's `toBytes` left-pads an odd-length hex string with a leading zero
    // nibble — so "0xdeadbeef1" hashes as the five bytes 0x0deadbeef1 while a text-level
    // `slice(0, 10)` reads the selector as 0xdeadbeef. The signer would then check the
    // mandate's selector and the vault's allowlist against four bytes that are NOT the first
    // four bytes of the calldata it committed to in `dataHash`. Found by adversarial review.
    if (v.length % 2 !== 0) fail(path, "an even number of hex digits (whole bytes)");
    if (bytes !== undefined && v.length !== 2 + bytes * 2) fail(path, `${bytes} bytes of hex`);
    return v.toLowerCase() as Hex;
}

function address(v: unknown, path: string): Hex {
    return hex(v, path, 20);
}

function bool(v: unknown, path: string): boolean {
    if (typeof v !== "boolean") fail(path, "a boolean");
    return v;
}

function str(v: unknown, path: string): string {
    if (typeof v !== "string") fail(path, "a string");
    return v;
}

/**
 * Rejects fields the signer does not understand instead of ignoring them.
 *
 * A dropped field is how one payload comes to mean two things to two components — the
 * evaluator believes it constrained something, the signer never saw it, and the receipt
 * attests to the weaker reading. Strictness here is cheap; the failure it prevents is not.
 */
function noExtras(o: Record<string, unknown>, allowed: readonly string[], path: string): void {
    for (const k of Object.keys(o)) {
        if (!allowed.includes(k)) throw new ProtocolError(`${path}: unexpected field ${JSON.stringify(k)}`);
    }
}

const MANDATE_FIELDS = [
    "schemaVersion", "mandateId", "principal", "signer", "vault", "chainId", "target", "targetCodeHash",
    "selector", "maxNativeValueWei", "purposeKind", "resourceId", "beneficiary", "durationSeconds",
    "recurringAllowed", "validAfter", "validUntil", "policyHash",
] as const;

export function parseMandate(v: unknown, path = "mandate"): MandatePayload {
    const o = obj(v, path);
    noExtras(o, MANDATE_FIELDS, path);
    return {
        schemaVersion: bounded(o.schemaVersion, `${path}.schemaVersion`, 16),
        mandateId: hex(o.mandateId, `${path}.mandateId`, 32),
        principal: address(o.principal, `${path}.principal`),
        signer: address(o.signer, `${path}.signer`),
        vault: address(o.vault, `${path}.vault`),
        chainId: bounded(o.chainId, `${path}.chainId`, 256),
        target: address(o.target, `${path}.target`),
        targetCodeHash: hex(o.targetCodeHash, `${path}.targetCodeHash`, 32),
        selector: hex(o.selector, `${path}.selector`, 4),
        maxNativeValueWei: bounded(o.maxNativeValueWei, `${path}.maxNativeValueWei`, 256),
        purposeKind: hex(o.purposeKind, `${path}.purposeKind`, 32),
        resourceId: hex(o.resourceId, `${path}.resourceId`, 32),
        beneficiary: address(o.beneficiary, `${path}.beneficiary`),
        durationSeconds: bounded(o.durationSeconds, `${path}.durationSeconds`, 64),
        recurringAllowed: bool(o.recurringAllowed, `${path}.recurringAllowed`),
        validAfter: bounded(o.validAfter, `${path}.validAfter`, 64),
        validUntil: bounded(o.validUntil, `${path}.validUntil`, 64),
        policyHash: hex(o.policyHash, `${path}.policyHash`, 32),
    };
}

const POLICY_FIELDS = [
    "schemaVersion", "policyVersion", "vault", "chainId", "allowedOperation", "allowedTargetsHash",
    "allowedSelectorsHash", "maxNativeValueWei", "maxAllowanceIncreaseBaseUnits",
    "allowedCallGraphHash", "validAfter", "validUntil", "failureMode",
] as const;

export function parsePolicy(v: unknown, path = "policy"): PolicyPayload {
    const o = obj(v, path);
    noExtras(o, POLICY_FIELDS, path);
    return {
        schemaVersion: bounded(o.schemaVersion, `${path}.schemaVersion`, 16),
        policyVersion: bounded(o.policyVersion, `${path}.policyVersion`, 32),
        vault: address(o.vault, `${path}.vault`),
        chainId: bounded(o.chainId, `${path}.chainId`, 256),
        allowedOperation: bounded(o.allowedOperation, `${path}.allowedOperation`, 8),
        allowedTargetsHash: hex(o.allowedTargetsHash, `${path}.allowedTargetsHash`, 32),
        allowedSelectorsHash: hex(o.allowedSelectorsHash, `${path}.allowedSelectorsHash`, 32),
        maxNativeValueWei: bounded(o.maxNativeValueWei, `${path}.maxNativeValueWei`, 256),
        // `bounded(..., 256)`, not `uint()` (A-068). Both fields are `uint256` on the wire and
        // both escaped the bound: an out-of-range value parsed fine and then threw inside
        // `leftPad` at signing time, giving a SIGNER_ERROR from within the signing routine
        // rather than a BAD_REQUEST at the boundary — which is exactly the defect A-044 fixed
        // for the other four integer fields and did not reach these two. The consequence is
        // D-012's: the one request a caller could trigger at will produced NO signed refusal
        // record, in the component whose record exists to make refusals provable.
        maxAllowanceIncreaseBaseUnits: bounded(
            o.maxAllowanceIncreaseBaseUnits, `${path}.maxAllowanceIncreaseBaseUnits`, 256),
        allowedCallGraphHash: hex(o.allowedCallGraphHash, `${path}.allowedCallGraphHash`, 32),
        validAfter: bounded(o.validAfter, `${path}.validAfter`, 64),
        validUntil: bounded(o.validUntil, `${path}.validUntil`, 64),
        failureMode: bounded(o.failureMode, `${path}.failureMode`, 8),
    };
}

const ACTION_FIELDS = [
    "schemaVersion", "chainId", "vault", "actionNonce", "target", "valueWei", "dataHash",
    "operation", "mandateHash", "policyHash", "deadline",
] as const;

export function parseAction(v: unknown, path = "action"): ActionPayload {
    const o = obj(v, path);
    noExtras(o, ACTION_FIELDS, path);
    return {
        schemaVersion: bounded(o.schemaVersion, `${path}.schemaVersion`, 16),
        chainId: bounded(o.chainId, `${path}.chainId`, 256),
        vault: address(o.vault, `${path}.vault`),
        actionNonce: bounded(o.actionNonce, `${path}.actionNonce`, 256),
        target: address(o.target, `${path}.target`),
        valueWei: bounded(o.valueWei, `${path}.valueWei`, 256),
        dataHash: hex(o.dataHash, `${path}.dataHash`, 32),
        operation: bounded(o.operation, `${path}.operation`, 8),
        mandateHash: hex(o.mandateHash, `${path}.mandateHash`, 32),
        policyHash: hex(o.policyHash, `${path}.policyHash`, 32),
        deadline: bounded(o.deadline, `${path}.deadline`, 64),
    };
}

const REQUEST_FIELDS = ["action", "callData", "mandate", "policy", "evaluation", "ttlSeconds"] as const;
const EVALUATION_FIELDS = [
    "verdict", "reasonCodes", "evidenceCanonical", "simulationBlockNumber", "simulationBlockHash",
] as const;

export function parseEvaluateAndSignRequest(v: unknown): EvaluateAndSignRequest {
    const o = obj(v, "params");
    noExtras(o, REQUEST_FIELDS, "params");

    const ev = obj(o.evaluation, "params.evaluation");
    noExtras(ev, EVALUATION_FIELDS, "params.evaluation");

    const verdict = str(ev.verdict, "params.evaluation.verdict");
    // `Object.hasOwn`, NOT `in` (A-061). `in` walks the prototype chain, so `__proto__`,
    // `toString`, `constructor` and every other Object.prototype member passed here as a legal
    // verdict name. The consequence was not cosmetic: on the refusal path the signer produced a
    // genuinely SIGNED §5.5.1 RefusalRecord whose `requestedVerdict` sits outside the published
    // schema, and the ratified D-010 verifier enforces that schema — so an unauthenticated
    // caller could choose a value that makes the signer's own proof-of-refusal unverifiable,
    // which is precisely what D-012's record exists to prevent. On the attest path the same
    // value reached `BigInt(verdictNumber(v))` and threw, returning SIGNER_ERROR from inside
    // the signing routine rather than BAD_REQUEST at the boundary.
    if (!Object.hasOwn(VERDICT, verdict)) fail("params.evaluation.verdict", "one of ALLOW, REVIEW, BLOCK");

    if (!Array.isArray(ev.reasonCodes)) fail("params.evaluation.reasonCodes", "an array");
    const reasonCodes = ev.reasonCodes.map((c, i) => {
        const code = str(c, `params.evaluation.reasonCodes[${i}]`);
        // Rejected at the boundary, so a malformed code is a BAD_REQUEST the caller can fix
        // rather than a signing-time throw. See REASON_CODE_PATTERN for why the shape is
        // load-bearing rather than cosmetic.
        if (!REASON_CODE_PATTERN.test(code)) {
            fail(`params.evaluation.reasonCodes[${i}]`, `to match ${REASON_CODE_PATTERN.source}`);
        }
        // THE SIGNER'S NAMESPACE IS THE SIGNER'S (A-044).
        //
        // `reasonCodesHash` commits to the UNION of the caller's codes and the signer's own
        // findings, and `signerFindings` is returned over the RPC but is NOT a field of the
        // signed §5.4 payload — so a third party reading a receipt cannot tell which side
        // contributed a code. Nothing rejected a caller-supplied `SIGNER_` prefix, and
        // `REASON_CODE_PATTERN` happily accepts one.
        //
        // An adversarial reviewer signed an ALLOW whose committed codes read
        // SIGNER_VAULT_PAUSED, SIGNER_MANDATE_NOT_ACTIVE and SIGNER_NOT_ACTIVE_SIGNER while
        // the signer had found nothing — an authenticated receipt asserting the signer said
        // three things it never said, and allowed anyway. Verdicts are unaffected
        // (`refusesVerdict` consults the signer's own findings only), which is exactly why
        // this is an integrity defect in the RECORD rather than a bypass.
        if (code.startsWith("SIGNER_")) {
            fail(
                `params.evaluation.reasonCodes[${i}]`,
                "not to use the SIGNER_ prefix, which is reserved for the signer's own findings",
            );
        }
        return code;
    });

    return {
        action: parseAction(o.action, "params.action"),
        callData: hex(o.callData, "params.callData"),
        mandate: parseMandate(o.mandate, "params.mandate"),
        policy: parsePolicy(o.policy, "params.policy"),
        evaluation: {
            verdict: verdict as VerdictName,
            reasonCodes,
            evidenceCanonical: wellFormed(
                str(ev.evidenceCanonical, "params.evaluation.evidenceCanonical"),
                "params.evaluation.evidenceCanonical",
            ),
            simulationBlockNumber: bounded(
                ev.simulationBlockNumber, "params.evaluation.simulationBlockNumber", 256),
            simulationBlockHash: hex(
                ev.simulationBlockHash, "params.evaluation.simulationBlockHash", 32),
        },
        ttlSeconds: o.ttlSeconds === undefined ? undefined : uint(o.ttlSeconds, "params.ttlSeconds"),
    };
}

// ---------------------------------------------------------------------------
// Serialisation
// ---------------------------------------------------------------------------

/** bigint → decimal string, recursively. The inverse of the parsers above. */
export function toWire(value: unknown): unknown {
    if (typeof value === "bigint") return value.toString();
    if (Array.isArray(value)) return value.map(toWire);
    if (typeof value === "object" && value !== null) {
        return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, toWire(v)]));
    }
    return value;
}
