#!/usr/bin/env bash
# Sentinel — project gate. Run this before claiming anything is green.
#
# Usage:
#   ./scripts/test.sh          fast profile (fuzz 1024)
#   ./scripts/test.sh --gate   deep profile for gate evidence (fuzz 20000)
#
# AGENTS.md: "a tool reporting success is not a substitute for checking its output",
# and a runner should fail on error output it does not explicitly expect. This script
# therefore fails on a non-zero exit from ANY stage, not just the last one.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
export PATH="$HOME/.foundry/bin:$PATH"

PROFILE="default"
[ "${1:-}" = "--gate" ] && PROFILE="gate"

fail=0
step() { printf '\n\033[1m== %s ==\033[0m\n' "$1"; }

step "secret guard (A-007)"
./scripts/check-secrets.sh || fail=1

step "rename gate (D-016)"
./scripts/check-rename-gate.sh || fail=1

step "labelling-prompt freeze (D-011a)"
./scripts/check-label-prompt.sh || fail=1

step "published EIP-712 type strings (D-023)"
./scripts/check-type-strings.sh || fail=1

step "§5.7.1 check coverage (D-031)"
./scripts/check-eval-codes.sh || fail=1

# Also reads its own output rather than its exit status. It passes on a RATCHET: six classes are
# carried as not-exercised-at-the-corpus-layer — one RESERVED, four DELEGATED elsewhere, and one
# a GAP that owes a fixture (D-039). A green line here means "no NEW class went vacuous", never
# "every class is covered". The carried list, the GAP count, and the per-fixture vacuity note
# print on every run for that reason.
step "corpus class coverage (A-036)"
./scripts/check-class-coverage.sh || fail=1

# Reads its own output, not just its exit status: this one passes on the mechanical half
# while printing two conditions only John can clear. A green gate here does NOT mean Gate 5
# is satisfied.
step "vendor honesty (§7.5 Gate 5, D-008)"
./scripts/check-vendor-honesty.sh || fail=1

step "solidity build + tests (profile: $PROFILE)"
if command -v forge >/dev/null 2>&1; then
    (cd contracts && FOUNDRY_PROFILE="$PROFILE" forge test -vv) || fail=1
else
    echo "forge not found. Install with: curl -L https://foundry.paradigm.xyz | bash && foundryup"
    fail=1
fi

# Ordered after the Solidity stage on purpose: the TypeScript suite deploys the compiled
# artifacts from contracts/out and runs the signer against the real vault, so it needs the
# build the previous stage produces. It also spawns Anvil, which the same toolchain supplies.
step "typescript typecheck + isolated signer suite (§9 step 3)"
if [ ! -d ts/node_modules ]; then
    echo "ts/node_modules missing. Run: npm --prefix ts ci"
    fail=1
elif ! command -v anvil >/dev/null 2>&1; then
    echo "anvil not found on PATH; the signer suite needs a local chain."
    fail=1
else
    npm --prefix ts run typecheck || fail=1
    npm --prefix ts test || fail=1

    # OBSERVATION, NOT A STAGE. D-007's canary "never fails CI", so this prints its recorded
    # history and cannot set `fail`. It is here because the other half of that ruling —
    # "an unobserved canary is not evidence" — is only satisfied if the history is put in
    # front of somebody on every gate run. NEVER RUN is a legitimate thing for it to print,
    # and it is louder here than in a file nobody opens.
    step "Gate 7 canary observation (D-007; never fails the gate)"
    npm --prefix ts run --silent canary -- --report || true

    # THE CORPUS, EXECUTED — deep profile only.
    #
    # `ts/src/corpus/run.ts` was covered by nothing: the suite never ran the corpus, which is
    # exactly why six deliberate defects in its wiring survived a fully green run. It is
    # executed here rather than left to a human remembering to run it.
    #
    # It writes to a TEMPORARY directory and the committed artifacts are not touched. What is
    # compared is `_digests.json` — each labeller view hashed with the run-varying timestamps
    # normalised out (A-029). So this stage asserts something the project could not assert
    # before: **the committed labeller views are still the semantic output of the current
    # code**, which is the provenance claim the corpus rests on and which git history alone
    # could not establish.
    #
    # THAT INFERENCE IS INVALID, AND IS REFUTED BY THE COMMENT ON THE DIGEST BRANCH BELOW
    # (A-048). `_digests.json` is regenerated by this run, so comparing it to the committed copy
    # compares the code to itself and says nothing about the committed view FILES. A-047 rewrote
    # the printed coverage boundary and left THIS header standing, unmarked — the same
    # "corrected one site of two" defect A-047 exists to record, inside A-047. The file-by-file
    # check below is what establishes the provenance; the digest comparison detects code drift.
    #
    # Deep profile only. It costs ~90s and would double the inner loop; the fast profile says
    # so out loud rather than silently skipping.
    if [ "$PROFILE" = "gate" ]; then
        step "§7.1 corpus executed, and the committed views verified (A-029)"
        CORPUS_TMP="$(mktemp -d)"
        if SENTINEL_CORPUS_OUT="$CORPUS_TMP" npm --prefix ts run --silent corpus >/dev/null 2>&1; then
            if diff -q "$CORPUS_TMP/for-labelling/_digests.json"                        fixtures/corpus/for-labelling/_digests.json >/dev/null 2>&1; then
                # THE DIGEST COMPARISON ABOVE DOES NOT DO WHAT THIS STAGE CLAIMED IT DID.
                #
                # `_digests.json` is REGENERATED by the run above, so the comparison is
                # fresh-digests versus committed-digests: both sides describe the code. That is
                # a real property — it detects CODE DRIFT, and it is why the mismatch branch
                # below exists — but the committed VIEW FILES are never hashed by it. An
                # adversarial review rewrote F001's `declaredIntent` and mandate ceiling,
                # touched nothing else, and this stage printed "committed views semantically
                # current" (A-047). The claim the corpus rests on — "these are the views the
                # labellers saw" — was not being checked at all.
                #
                # So compare the committed view FILES against the ones just produced, with the
                # run-varying fields `_digests.json` itself declares (A-029) stripped from both
                # sides. The declared exception list is read from the file rather than hardcoded
                # here, so a new normalised field cannot silently widen this check.
                if python3 - "$CORPUS_TMP/for-labelling" fixtures/corpus/for-labelling <<'VIEWCHECK'
import glob, json, os, sys
fresh_dir, committed_dir = sys.argv[1], sys.argv[2]
norm = set(json.load(open(os.path.join(committed_dir, "_digests.json"))).get("normalisedFields") or [])

# PIN THE EXEMPTION LIST. It is read from `_digests.json`, which the corpus run REGENERATES, so
# a one-line edit to RUN_VARYING_FIELDS in ts/src/corpus/run.ts silently widens what this check
# ignores — and an earlier comment here claimed the opposite mechanism (A-048). The list is now
# asserted. Widening it is a decision that has to be made in this file, in the open.
EXPECTED_NORM = {"expiryBefore", "expiryAfter"}
if norm != EXPECTED_NORM:
    print("  NORMALISED-FIELD LIST CHANGED — expected %s, got %s."
          % (sorted(EXPECTED_NORM), sorted(norm)))
    print("    This list is what the view comparison IGNORES. Widening it weakens the check.")
    print("    If the change is intended, argue for it here and update EXPECTED_NORM.")
    sys.exit(1)

# THESE TWO FIELDS ARE NOT DISPLAY TIMESTAMPS, AND CALLING THEM THAT WAS A DEFECT (A-048).
# `ts/src/evaluate/checks.ts` derives EVAL_ENTITLEMENT_ADVANCED from `expiryAfter > expiryBefore`,
# so the pair is a CONFORMANCE INPUT that appears in 36 of the 50 committed views. Stripping both
# outright — as the first version did — left an arbitrary-value channel inside a decision-relevant
# field: a reviewer set F001's `expiryAfter` to "0", flipping the check the labelling view would
# fail, and the deep gate printed "committed views verified FILE BY FILE" and passed.
#
# The RELATION does not vary and is the thing the evaluator reads, so it is compared instead of
# discarded.
#
# **THE STATED JUSTIFICATION WAS FALSE FOR HALF OF IT (A-051).** "Absolute values genuinely vary
# with chain time" holds for `expiryAfter`; `expiryBefore` is measured to be the constant `"0"` in
# 35 of the 36 views that carry the pair. It does not vary at all, so exempting it has no
# chain-time justification — and `"0"` versus nonzero is the difference between a first purchase
# and a renewal, a distinct fact for the labeller. **Also unclosed: the relation comparison is
# TYPE-BLIND** — `int()` normalises `"9"` and `9`, so a committed view can change its JSON schema
# undetected. Both are recorded in `docs/v1-1-register.md` §8 rather than fixed here.
def strip(o):
    if isinstance(o, dict):
        if "expiryAfter" in o and "expiryBefore" in o:
            try:
                advanced = int(o["expiryAfter"]) > int(o["expiryBefore"])
            except (TypeError, ValueError):
                advanced = "UNPARSEABLE:%r/%r" % (o.get("expiryBefore"), o.get("expiryAfter"))
            kept = {k: strip(v) for k, v in o.items() if k not in norm}
            kept["__entitlementAdvanced"] = advanced
            return kept
        return {k: strip(v) for k, v in o.items() if k not in norm}
    if isinstance(o, list):  return [strip(v) for v in o]
    return o
names = lambda d: {os.path.basename(p) for p in glob.glob(os.path.join(d, "F*.json"))}
fresh, committed = names(fresh_dir), names(committed_dir)
bad = []
if fresh != committed:
    bad.append("file set differs: only-committed=%s only-fresh=%s"
               % (sorted(committed - fresh), sorted(fresh - committed)))
for n in sorted(fresh & committed):
    if strip(json.load(open(os.path.join(committed_dir, n)))) != strip(json.load(open(os.path.join(fresh_dir, n)))):
        bad.append(n)
if bad:
    print("  committed view FILES differ from what this code produces:")
    for b in bad[:10]:
        print("    %s" % b)
    if len(bad) > 10:
        print("    ...and %d more" % (len(bad) - 10))
    sys.exit(1)
print("  %d committed view files match the current code — %s compared by RELATION "
      "(expiryAfter > expiryBefore, the EVAL_ENTITLEMENT_ADVANCED input); their absolute "
      "values are NOT compared, and only expiryAfter's variance justifies that"
      % (len(fresh & committed), "/".join(sorted(norm))))
VIEWCHECK
                then
                    echo "corpus: 50 fixtures executed; committed views verified FILE BY FILE"
                else
                    echo "corpus: COMMITTED VIEWS TAMPERED OR STALE — the digests match the code,"
                    echo "  but a committed view file is not what the code produces. The labels of"
                    echo "  record were drawn against the COMMITTED views, so this invalidates them"
                    echo "  until explained. Re-run 'npm --prefix ts run corpus' and commit, or find"
                    echo "  out who edited a view. Do NOT repin by regenerating without reading the diff."
                    fail=1
                fi
            else
                echo "corpus: DIGEST MISMATCH — the committed labeller views are NOT what this"
                echo "  code now produces. Either re-run 'npm --prefix ts run corpus' and commit"
                echo "  the result, or find out what changed. The labels of record were drawn"
                echo "  against the COMMITTED views."
                diff "$CORPUS_TMP/for-labelling/_digests.json"                      fixtures/corpus/for-labelling/_digests.json | head -20
                fail=1
            fi
        else
            echo "corpus: RUN FAILED. Note the recorded trace: the runner picks a random port"
            echo "  and occasionally collides, so re-run once before diagnosing."
            fail=1
        fi
        rm -rf "$CORPUS_TMP"
    else
        step "§7.1 corpus (SKIPPED — fast profile)"
        echo "corpus: not executed. Use --gate; ts/src/corpus/run.ts is covered by nothing else."
    fi
fi

# THE D-010 VERIFIER, EXECUTED.
#
# Added 2026-08-16 (A-045). Until then this stage did not exist: the verifier's own suite was
# invoked by NO profile of this script and by nothing else in `scripts/`, so its 146 tests
# passed only when a human remembered to run them by hand. Its counts were nonetheless quoted
# in `docs/session-state.md` §3 alongside the Foundry and TypeScript ones, as though a green
# gate covered them. It did not. A regression in the verifier could not have failed this gate.
#
# That is this project's most-repeated defect — an instrument that exists and is wired to
# nothing (D-042's invariant arms, A-036's class claims) — sitting in an S2 DELIVERABLE.
#
# Deliberately OUTSIDE the node_modules/anvil block above: D-010 requires the verifier share no
# code and no language with the evaluator, and a stage that inherits the TypeScript stage's
# preconditions would quietly couple them. It needs python3 and nothing else — the suite is
# stdlib `unittest` and the CLI has zero third-party imports, so wiring it in adds no
# dependency the repository did not already have.
#
# BOTH arms run, because they fail differently: the suite proves the verifier's internals,
# and the sample walk proves it still certifies the COMMITTED artifacts. A verifier that
# passes its own tests while rejecting the corpus is the failure this second arm catches.
# FLOORS. Added 2026-08-16 (A-047) after an adversarial review showed the first version of this
# stage could not detect the verifier SHRINKING. Un-prefixing one test method produced a run that
# printed "Ran 145 tests" and "146/146 of its own tests pass" in the same output, gate green —
# because the counts were emitted by the run and QUOTED separately in the coverage boundary, with
# nothing reconciling them. That is precisely the defect A-045 was written to close, reproduced
# inside A-045's own remediation. These three numbers are the assertion. Raise a floor when the
# suite genuinely grows; NEVER lower one to make a run pass.
VERIFIER_MIN_TESTS=158
VERIFIER_MIN_SAMPLES=7
VERIFIER_MIN_TAMPER=62
# A MODE FLOOR, because a pair count alone rewards padding (A-049): `tamper cases` counts
# (sample x mode) pairs, so ADDING a sample raises it whether or not modes were deleted.
#
# **"DISTINCT MODES CANNOT BE PADDED THAT WAY" WAS FALSE AND IS WITHDRAWN (A-051).** A reviewer
# replaced the real `signature` mode with a registered no-op — added to `TAMPER_MODES`, added to
# `TAMPER_MUST_STILL_VERIFY` so it need not mutate anything, and given an empty branch — and the
# gate reported `tamper 63 cases / 24 modes (floors 62/24)`: the pair count went UP while the mode
# proving a corrupted receipt signature is rejected no longer existed. Verified. A mode is a NAME,
# and a name costs nothing. `TAMPER_MUST_STILL_VERIFY` is an author-writable exemption from having
# to mutate at all. **Both floors are ratchets against accident, not against intent.** What
# actually defends a specific mode is a structural test naming it — `test_the_mode_is_declared`
# does that for `evidence-hash`, and no other mode has one.
VERIFIER_MIN_TAMPER_MODES=24

step "D-010 receipt verifier (independent Python; §14.2, D-010)"
if command -v python3 >/dev/null 2>&1; then
    v_fail=0

    # THREE arms, not two. The third is new: the tamper suite was never executed by this gate,
    # so "55/55 applicable tamper cases" was a figure no run produced. `--tamper all` REPLACES
    # normal verification rather than adding to it, which is why the plain walk stays.
    #
    # 2>&1 is load-bearing on the first arm: unittest writes to stderr, so redirecting only
    # stdout silently drops this arm's whole output — including the count the floor reads.
    # THE SUITE'S OWN TEXT REPORT IS NOT EVIDENCE ABOUT THE SUITE (A-051). THREE VERSIONS OF
    # THIS CHECK WERE DEFEATED BEFORE THIS ONE, AND EACH FIX ADDRESSED THE DEMONSTRATION.
    #
    #   v1 (A-045) asserted the exit status only. Beaten by `@unittest.skip`.
    #   v2 (A-047) asserted `Ran N >= 146`. Beaten again: unittest COUNTS skipped and
    #      expected-failure tests inside `Ran N`, so a `setUp` monkeypatched to `skipTest` gave
    #      `Ran 146 / OK (skipped=146)` — every assertion disabled, 15s to 0.003s — and passed.
    #   v3 (A-048) asserted a bare `OK` verdict line, parsed from `2>&1`. Beaten by TWO LINES:
    #      the skip, plus `print("OK")`. unittest writes its verdict to line-buffered STDERR
    #      while a test file's stdout is block-buffered to the pipe and flushed at interpreter
    #      exit — i.e. AFTER the verdict — so `tail -1` took the injected line and the gate
    #      printed `verdict OK` with all 149 assertions disabled. Found independently by two
    #      reviewers in the same round.
    #
    # THE ARGUMENT, which v1-v3 all missed: the file under test also writes the report the gate
    # reads. Parsing that report is asking the suspect for its own alibi, and moving to stderr
    # would not help — a test can write there too. So this reads the RESULT OBJECT instead.
    # `skipped`, `expectedFailures` and `unexpectedSuccesses` are structural properties of the
    # run that no amount of printing can alter, and the counts are written to a temp file rather
    # than to a stream the suite shares.
    v_res="$(mktemp)"
    python3 - "$v_res" <<'VERIFIERRUN' >/dev/null 2>&1
import io, os, sys, unittest
sys.path.insert(0, os.path.join(os.getcwd(), "verifier"))
res = unittest.TextTestRunner(stream=io.StringIO(), verbosity=0).run(
    unittest.defaultTestLoader.loadTestsFromName("test_verifier"))
with open(sys.argv[1], "w") as fh:
    fh.write("%d %d %d %d %d %d\n" % (
        res.testsRun, len(res.skipped), len(res.expectedFailures),
        len(res.unexpectedSuccesses), len(res.failures), len(res.errors)))
VERIFIERRUN
    v_tests=""; v_skip=""; v_xfail=""; v_xpass=""; v_vfail=""; v_verr=""
    read -r v_tests v_skip v_xfail v_xpass v_vfail v_verr < "$v_res" 2>/dev/null || true
    rm -f "$v_res"

    # FAIL CLOSED on an unreadable report: a crashed or hung runner must not read as clean.
    if [ -z "${v_tests:-}" ]; then
        echo "  VERIFIER SUITE PRODUCED NO REPORT — treating as failure, not as clean."
        v_fail=1; v_tests=0; v_skip=0; v_xfail=0; v_xpass=0; v_vfail=0; v_verr=0
    fi

    v_verdict="clean"
    for probe in "skipped:$v_skip" "expected-failures:$v_xfail" \
                 "unexpected-successes:$v_xpass" "failures:$v_vfail" "errors:$v_verr"; do
        p_name="${probe%%:*}"; p_n="${probe##*:}"
        if [ "${p_n:-0}" -ne 0 ] 2>/dev/null; then
            echo "  SUITE NOT CLEAN — $p_name: $p_n"
            echo "    A test that is skipped, expected to fail, or unexpectedly succeeds RAN"
            echo "    without asserting what it names. Argue for it here, in the open."
            v_verdict="$p_name=$p_n"
            v_fail=1
        fi
    done

    s_out="$(python3 verifier/verify.py --all fixtures/samples 2>&1)" || v_fail=1
    v_samples="$(printf '%s\n' "$s_out" | sed -n 's#^\([0-9][0-9]*\)/[0-9][0-9]* sample(s) verified.*#\1#p' | tail -1)"

    t_out="$(python3 verifier/verify.py --all fixtures/samples --tamper all 2>&1)" || v_fail=1
    v_tamper="$(printf '%s\n' "$t_out" | grep -c 'tamper self-test PASS' || true)"
    v_modes="$(printf '%s\n' "$t_out" | grep -oE 'the mutated [a-z-]+' | sed 's/the mutated //' | sort -u | wc -l | tr -d ' ')"

    # The verdict is printed even on success, deliberately. Making this stage quiet was itself a
    # finding: at fac9140 the suite ran unredirected, so `OK (skipped=N)` would have reached the
    # gate log, and capturing the output DELETED the one channel that would have exposed the
    # defeat above. Foundry and TypeScript both print their skip counts on every run; this stage
    # now says the same thing in one line.
    echo "  suite ${v_tests:-0} (floor $VERIFIER_MIN_TESTS) · verdict ${v_verdict:-NONE} · samples ${v_samples:-0} (floor $VERIFIER_MIN_SAMPLES) · tamper ${v_tamper:-0} cases / ${v_modes:-0} modes (floors $VERIFIER_MIN_TAMPER/$VERIFIER_MIN_TAMPER_MODES)"

    for probe in "tests:${v_tests:-0}:$VERIFIER_MIN_TESTS" \
                 "samples:${v_samples:-0}:$VERIFIER_MIN_SAMPLES" \
                 "tamper cases:${v_tamper:-0}:$VERIFIER_MIN_TAMPER" \
                 "tamper modes:${v_modes:-0}:$VERIFIER_MIN_TAMPER_MODES"; do
        p_name="${probe%%:*}"; p_rest="${probe#*:}"; p_got="${p_rest%%:*}"; p_want="${p_rest##*:}"
        if ! [ "$p_got" -ge "$p_want" ] 2>/dev/null; then
            echo "  FLOOR BREACHED — $p_name: $p_got, floor $p_want. THE VERIFIER SHRANK."
            echo "    A count nothing asserts is a count that shrinks silently."
            v_fail=1
        fi
    done

    # Quiet on success — this stage emits ~450 lines, and it sits immediately before the block
    # whose own header says "read this, not the pass count". On any failure everything prints,
    # because that is when it is worth reading.
    #
    # The suite is RE-RUN here for its text, rather than the text being captured up front. That
    # text is DIAGNOSTIC ONLY and is never the assertion — the assertion is the result object
    # above, for the reasons in the comment there. Note also that `$v_out` used to be referenced
    # on this line and no longer exists; under `set -u` that would have errored, but only on runs
    # where something had ALREADY failed, which is the worst place to hide a defect (A-051).
    if [ "$v_fail" -ne 0 ]; then
        echo "  --- verifier suite detail (re-run; diagnostic only) ---"
        python3 verifier/test_verifier.py 2>&1 | tail -40 || true
        printf '%s\n' "$s_out" "$t_out"
        fail=1
    fi
else
    echo "python3 not found; the D-010 verifier is the independent check on every receipt."
    fail=1
fi

printf '\n'
if [ "$fail" -ne 0 ]; then
    echo -e "\033[31mGATE FAILED\033[0m"
    exit 1
fi

cat <<'COVERAGE'
GATE PASSED

================================================================================
COVERAGE BOUNDARY (house rule 4) — read this, not the pass count
================================================================================

MAINTENANCE NOTE, because this block previously rotted: it is ONE statement, not a
running log. Two outside reviewers found it simultaneously claiming that the Anvil
pipeline and conformance engine did not exist, that Case 3 was undetectable, and — four
lines later — that Case 3 was detectable. A self-contradicting boundary is worse than
none, because a reader takes whichever half suits them, which is the exact failure the
boundary exists to prevent. When a step lands, REWRITE the affected layer below. Do not
append.

WHAT IS COVERED, by layer, each with the limit that layer cannot exceed:

  §9 s1-2  Vault + typed payloads. Exact-action binding, nonce single-use, verdict
           gating, override binding, pause, owner-only controls, signer rotation,
           reentrancy, and stateful invariants over all of it. The override path is IN
           the stateful campaign as of 2026-08-15 — before that the entire second
           execution path, the one that moves funds on a REVIEW verdict, appeared only
           in deterministic tests. `SentinelVault.backstops.t.sol` adds thirteen tests
           each named for a deliberate defect that SURVIVED a green 43-test run, among
           them §3.3(9)'s "nonce consumed before the external call", which the
           reentrancy guard masks and which nothing had ever verified. A second review then
           found five MORE survivors, three of them properties the contract's own comments
           claim: `nonReentrant` droppable from the OVERRIDE path (a double-spend, on two
           shapes, since the guard is shared), the override's binding to one exact review
           receipt untested, and `CallFailed` asserted by nothing. Covered now.
           LIMIT: proves the vault ENFORCES a receipt, never that the receipt carried a
           CORRECT verdict. A vault that faithfully executes a wrong decision passes
           every one of these tests. The invariant handler's action set also defines
           what "cannot bypass" was tested against: a path it never generates was not
           tested.

  §9 s3    Isolated signer, as a separate OS process behind a two-method 0600 socket.
           All 33 declared checks triggered individually; every severity tier asserted
           against all three verdicts; the per-nonce guard under real concurrency.
           LIMIT: proves the signer refuses a MIS-BOUND receipt. In these tests the
           verdict is an INPUT, so a signer faithfully attesting to a wrong ALLOW passes
           all of them.

  §9 s4    Two decoders. Every declared refusal triggered individually, plus a measured
           comparison against the real EVM: never more permissive than the chain,
           stricter in exactly one place (trailing bytes).
           LIMIT: proves faithfulness to bytes. Renders no verdict.

  §9 s5    Anchored snapshot/execute/inspect/revert pipeline against a real Anvil.
           Leak-freedom on success and revert paths, repeatability, an anchor surviving
           the revert, effects measured with the VAULT as msg.sender.
           LIMIT: effects are SIMULATED at a recorded block, not observed
           post-execution (§8 as amended by D-001).

  §9 s6    Conformance engine + RFC 8785 evidence bundle. The §5.2 verdict fold; all 41
           declared checks triggered individually; all four §4.2 cases end to end, with
           Case 1 continuing through the signer into the vault. Case 3 IS detected here,
           blocked on mandate conformance while every representative-baseline check
           passes. Three independent EIP-712 implementations agree.
           LIMIT: this is the layer whose own tests prove least. Self-written tests
           encode the same misunderstanding twice.

  §9 s7    Agent-proposal transcriber, and the pipeline driven from real agent output.
           Both arms of the pinned claude-haiku-4-5 recording (A-009) run through
           decode, simulation, evaluation, isolated signing and the vault: the control
           proposal executes and writes an entitlement onchain, the injected proposal
           blocks with no executable receipt. All 7 declared refusals triggered
           individually, each of their alternate branches too, with a structural
           exhaustiveness assertion over the code table.
           LIMIT: under D-019 Sentinel ENCODES the calldata from the agent's typed
           arguments, so the decoder recovering the agent's claimed parameters is a
           round-trip through Sentinel's own encoder and NOT independent corroboration.
           What is genuinely demonstrated is that the agent's rationale — its account of
           what the call means — reaches no check, no bound field, and no byte of the
           evidence bundle. Two further limits: the transcriber emits only exact-width
           canonical words for the SIGNATURE THE AGENT SUPPLIED — but that is not the
           same as the word count the decoder expects, because the decoder keys off a
           4-byte truncated keccak of that signature. A selector collision inside the
           transcriber's own grammar therefore makes §7.1's malformed-calldata class
           REACHABLE from a proposal; an adversarial review demonstrated one
           (`fUXSEz2ajwh(bytes32)` collides with `purchase(...)`, found in 106 seconds).
           It fails CLOSED — the decode failure is UNRESOLVED, so no wrong ALLOW — but the
           earlier wording here claimed unreachability as an absolute and was false (A-028).
           The malformed classes are still authored as raw calldata in the corpus. And the
           proposals are PINNED transcripts, which fix the agent's output and therefore say
           nothing about whether the injection still reproduces against a live model. That
           gap is now covered OUTSIDE this suite by the D-007 canary (`npm --prefix ts run
           canary`), whose history this script prints; nothing in the suite itself calls a
           model, and the canary is deliberately not a stage here.

  §9 s8    The §7.1 corpus and the §7.3 ablation. 50 fixtures spread over all 20 declared
           classes — but SPREAD OVER IS NOT COVERAGE, and as of 2026-08-16 the difference is
           measured rather than assumed: check-class-coverage.sh (A-036) finds 14 of the 20
           produce a failing check the class is actually about. Six do not. Four of those are
           known and reasoned — the call-graph class D-025 reserved, the signer class the
           evaluator has no code for, the injection class whose subject is containment rather
           than a check, and the override class the vault suite proves instead. THE SIXTH IS A
           GAP (D-039): `conflicting-block-state` declares it is proved by the conformance
           engine, is not, and nothing else covers it. It owes a fixture at v1.1.
           A DELEGATION IS NOT A CREDIT. Where a class points elsewhere, this guard reports the
           pointer; it cannot see the delegate and does not check that the delegate tests
           anything. One of the four points at a REGRESSION guard that is explicitly not a
           proof of absence. Read the carried list the guard prints; a green line there means
           no NEW class went vacuous.
           The class number also hides per-fixture vacuity, which the guard now prints
           separately: 39 of 43 scoped fixtures individually fail a check their OWN class is
           about. A class stays green while a member of it exercises nothing — F051 was caught
           only because it was the sole fixture of its class.
           The fixtures are executed against a real chain with per-fixture snapshot isolation, and
           INDEPENDENTLY LABELLED under the D-011a frozen prompt by agents denied the
           implementation, the tests, and each other's work. Measured against those labels:
           false allows 38 (baseline) / 8 (policy+effects) / 1 (full). Detection
           contribution — baseline alone 9, effect extraction adds 29, mandate conformance
           adds 8, and those 8 are exactly the wrong-purpose class (D-034 gave the partition
           a criterion and moved nine non-purpose codes to L2; the figure was 17). Inter-labeller disagreement 0.0% on a freshly drawn sample, with FOUR
           limits on that number stated in the report — two written with it, two supplied by
           an independent review.
           LIMIT ON THE EXACT-MATCH COLUMN: 12/50, 41/50, 49/50 are scored against labeller E,
           and the one label the contamination channel moved (F051) is one of the 50. Scored
           without it the figures read 11/49, 40/49, 48/49. Both columns are real; only the
           first is published anywhere but the decision log (A-033).
           LIMIT: this is the first evidence in the repository that bears on whether the
           verdicts are RIGHT rather than merely produced, and it is bounded by the corpus.
           50 fixtures over two demo contracts and two call schemas is not an accuracy claim
           about EVM transactions (§7.3: "do not claim general transaction-safety accuracy").
           The `malicious-retrieved-instructions` class carries a real rationale as of
           2026-08-15, and the run measures that no derived adjacent word-pair of it — nor a
           base64 or hex carriage of the whole — reaches a bound field, a check, a reason
           code, or the evidence bundle. That is a REGRESSION guard, not a proof of absence:
           a single leaked word, a paraphrase, or an unanticipated encoding passes. NO LAYER
           DETECTS AN INJECTION and none should: nothing reads the narrative, so a layer that
           appeared to would be a defect.
           The single full-configuration false allow is F035, whose enforcement is the
           isolated signer rather than the engine. The labels of record are the THIRD round
           (E/F): round 1 scored a spec since amended, and round 2 was discarded as
           contaminated when a review found the brief had handed the labeller a finding
           derived from reading the evaluator (A-028 F-1). All earlier rounds are retained
           as audit trail.

  D-010    The independent Python receipt verifier, in `verifier/`. Zero third-party
           dependencies; its own RFC 8785, Keccak-f[1600] and secp256k1 recovery, built by
           an agent that never read this repository's TypeScript. 7/7 samples verify, 62/62
           applicable tamper cases across 24 distinct modes behave as specified, and 149/149
           of its own tests pass.
           It verifies REFUSALS as well as decisions as of 2026-08-16: §5.5.1's
           RefusalRecord was implemented by a schema-only agent and met a real signed
           refusal it had never seen, which is where the envelope gap and three further
           defects in that section came from (A-042). One sample commits to exactly ONE
           reason code — until 2026-08-15 nothing pinned that edge, and a producer
           appending the delimiter after a one-element set would have verified here
           (A-027). Its keccak is pinned to published vectors and its JCS to RFC 8785's
           appendix-B vectors, so green means agreement with the STANDARD, not with itself.
           ALL THREE FIGURES ARE FLOORS THIS RUN ASSERTS (A-047) — if the verifier shrinks,
           the gate fails and prints FLOOR BREACHED. That took two attempts, and the first
           one's failure is the more useful record. Until 2026-08-16 no profile ran the
           verifier at all and these numbers read 6/6, 42/42, 70/70 — stale through A-041
           (70 → 101) and A-042 (101 → 146, plus the seventh sample). A-045 wired the arms
           in and checked only their EXIT STATUS, so the figures stayed quoted prose beside
           a run that produced different ones: an adversarial review disabled one test
           method and got "Ran 145 tests" and "146/146 of its own tests pass" in a single
           green run. The tamper figure was worse — no arm ran `--tamper`, so 55 was
           produced by nothing at all. Both closed by the floors above, falsified against
           the real script.
           THAT HOLE IS NOW CLOSED, and the shape of it is worth keeping. Until 2026-08-17
           `ok = True or evidence_hash == expected_hash` — neutering the evidenceHash check by
           hand — left all 146 tests passing and all 7 samples verifying, because no tamper
           mode mutated `evidence.hash`: the field was only ever READ. A named check that no
           mode targets is a check nothing asserts. The `evidence-hash` mode (A-049) corrupts
           the PUBLISHED hash rather than the canonical bytes, so it isolates that one check;
           the same neutering now produces 12 failures. Its three tests are written the hard
           way — the mode's presence in TAMPER_MODES asserted structurally, the mutated bundle
           required to fail ON THAT CHECK specifically, and the UNMUTATED bundle required to
           pass it, so the test cannot succeed by the check always failing.
           LIMIT THAT REMAINS: the floors catch a verifier that SHRINKS and this mode catches
           one named check that stops checking. Neither generalises. No mutation sweep has been
           run over `verify.py` itself, which is 1681 lines and DECIDES the verdict. A directed
           sweep of the SIX other modules (A-051) applied 142 behaviour-changing mutations
           and 41 survived a green gate — `keccak.py` was clean at 17/17, `jcs.py` caught
           23/33, and `eip712.py` and `secp256k1.py` were thin: construction pinned,
           value-level validation almost unexercised. Three verdict-flippers from that sweep
           are now closed; the rest are in the register. THE COUNT WAS ALSO WRONG HERE — it
           read 'five modules' and omitted `jcs.py`, the RFC 8785 canonicalizer, which is
           where two of the sweep's best findings turned out to be.
           LIMIT: it verifies that a bundle is the one a receipt commits to and that the
           receipt is correctly signed. It CANNOT confirm the bundle's factual content
           against a chain — that needs an archive node at the anchored block. Verifying a
           receipt is not verifying the simulation. The corpus exercises no JSON numbers and
           no non-ASCII, so RFC 8785's number and code-unit-ordering paths — its two most
           error-prone branches — are untested by anything (REPORT.md F-6).

WHAT IS NOT COVERED:

  - A LIVE agent. §9 step 7 connected the proposal to the pipeline, so the D-018 gap is
    closed for the recorded case, but every agent proposal exercised here comes from a
    pinned D-007 transcript. Nothing in this suite calls a model.
  - THAT THE VAULT CONSTRAINS TOKEN AUTHORITY. It does not, and §7.1 said otherwise until
    2026-08-16 (D-042). The hard caps bound the NATIVE-VALUE dimension only: pause, nonce,
    deadline and the wei ceiling. One valid ALLOW receipt for approve(spender, max) passes
    every onchain check — the wei ceiling never engages, valueWei being zero — and the
    vault's whole token balance becomes transferable. The flagship Case 2 attack is
    refused by the EVALUATOR with nothing behind it. A per-action allowance ceiling is
    v1.1; test_LIMIT_vaultCapsNativeValueOnlyAndNotTokenAuthority asserts the limit so it
    cannot regress into an assumption.
  - WHAT THE STATEFUL CAMPAIGN ADDS OVER THE DETERMINISTIC TESTS. Measured 2026-08-16 and
    the answer was NOTHING: 31 mutations, 31/31 caught by the 56 deterministic tests, and
    31/31 still caught with the whole campaign disabled. Five survived all invariants,
    including a vault accepting arbitrary FUTURE nonces. Two arms were added (D-042) and
    both of those mutations are now killed — but the honest reading of Gate 6's line is
    that the deterministic tests carry it and the campaign corroborates. A campaign's
    coverage is bounded by what its handler can BUILD, not by its call count.
  - THAT GATE 5's CITATIONS SAY WHAT §2 CLAIMS THEY SAY. Certified by John 2026-08-16
    (D-038); the check reports 11 of 11 rows and "certified by record" rather than
    UNCERTIFIED. Two claims that stood here until 2026-08-16 were false, both understating
    the instrument (A-046). It DOES resolve §13#N against §13's actual entry numbers — a
    probe citing §13#997 fails with "§2 cites §13 entries that do not exist" — and an edit
    to the §2 table IS detected, the certified table being pinned by hash, so a probe
    inserting one row reports the certification STALE and Gate 5 NOT MET. That expiry is an
    instrument, not a convention.
    THAT CORRECTION THEN OVERSHOT, and this is the repaired wording (A-047). THE RESOLVER
    READS THE CAPABILITY CELL ONLY — awk field 4. A `[§13#997]` marker in the "Consequence
    for Sentinel" cell resolves against nothing and is caught today only because the hash
    pin happens to notice the edit; re-certification clears that pin and leaves the bad
    citation unchecked. D-008(1) covers every cell of the matrix, so that is inside the
    condition, not outside it. The previous wording carried the "in the capability cell"
    scope and the correction deleted it while broadening the verb.
    THE DATE IS STILL SHAPE-ONLY, a limitation the correction dropped and this restores —
    but CONDITIONALLY, which the first restoration got wrong (A-048). `[§13#9 read 1999-01-01]`
    does NOT pass today: it edits §2, so the hash pin reports the certification STALE and the
    guard exits 1. What is unchecked is the DATE ITSELF — nothing compares it to §13's entry or
    to D-038's certified access date of record — so once the table is re-certified for any
    reason, a stale or invented read date rides through unexamined. Same conditional as the
    Consequence-cell case above: caught today by the pin noticing the edit, not by the date
    being verified. Claiming it "passes" outright overstated the gap.
    ALSO: the "11 of 11 rows carry a marker resolving to a §13 entry" line prints even on
    runs where the resolver FAILS on a specific N — the counter matches marker SHAPE and the
    resolver is a separate pass whose result never reaches it. Read the FAIL lines, not that
    counter.
    WHAT NO INSTRUMENT HERE CAN REACH is whether a resolvable, dated citation ACTUALLY
    SUPPORTS the capability claim in its row. The guard says so itself — though only on the
    branch where the mechanical conditions pass, so a STALE run does not print that caveat.
    D-038's source-verification pass found five of nine rows unsupported by their cited
    pages. That is the count of record; an earlier version of this bullet referred to "the
    sixth", which has no referent in the audit, D-038 or A-039. Note also that D-038 split
    two rows, which is why nine rows became the eleven counted above.
  - The evidence dashboard (outside S2 unless John adds it at the gate, D-009).
  - Gate 8 (five-minute comprehension), which D-032 makes PRE-PUBLICATION rather than S2.
  - BYTE-reproducible labelling views: a corpus re-run rewrites 32 of 50 view files
    purely because entitlement expiry follows chain time (A-029). What IS covered, at
    the deep profile, is that the committed views are SEMANTICALLY current — the corpus
    runs to a temp directory and its 50 view FILES are compared to the committed ones, the
    entitlement expiry pair by RELATION (`expiryAfter > expiryBefore`, the input to
    EVAL_ENTITLEMENT_ADVANCED) since its absolute values follow chain time. "These are the
    views the labellers saw" is checkable on that basis rather than resting on git history
    alone. TWO CORRECTIONS TO WHAT THIS SAID BEFORE 2026-08-17 (A-048): the DIGEST comparison
    was never what established this — it compares the code to itself — and the expiry pair is
    not a "declared timestamp field" but a conformance input that was exempt from every layer,
    in 36 of 50 views, until the relation check was added.
  - Labeller independence from PRIOR FINDINGS about specific fixtures (A-030) is no
    longer an open fork — it was MEASURED (D-033, D-035) and the channel moved exactly
    ONE label, F051, the one labeller E had flagged itself. What is NOT covered is the
    residue: the specification still carries fixture walkthroughs and still publishes
    41 of the evaluator's reason-code identifiers, a contamination surface four times
    what the decision log recorded before it was counted. v1.1 work, not measured away.
  - Model-INDEPENDENT labelling. One arm used a different Claude model and agreed. The
    build loop cannot obtain a labeller from another vendor, so "model diversity" here
    means a second model from one family, not an independent implementation of judgement.
  - An independent review of steps 1-3, whose earlier pass (A-016) had most of its
    verifications cut short by a spend limit that is NOT retired. Steps 4-6 had a full
    independent adversarial pass under D-017 (see A-022): fixed commit, 12 findings, all 12
    independently adjudicated, 1 S1-blocking defect plus 6 others corrected and reverified.
    Steps 7-8 were reviewed 2026-08-15: ten findings, all remediated.
    Steps 1-3 were reviewed earlier under A-016, whose own verifications were mostly cut
    short by a spend limit — that limit is NOT retired by the later review.

A green run means the mechanism runs end to end. It does not mean Sentinel decides
correctly. Those are different claims and only the first is in evidence here.

For gate evidence use the deep profile — ./scripts/test.sh --gate — not this default.
COVERAGE
